### ISSUE TITLE
streaming video API

### ISSUE THREAD

**Issue by 4bhis1** [Nyumat/NyumatFlix#6]
Hey Nyumat,

Its not an issue, but I don't got any other way to ask you about API you'e using to stream videos with help of tmdb id.

Waiting for your response....

**Comment by Nyumat** [comment]
Hello @4bhis1,

Thanks for reaching out. Although, what exactly are you asking?

**Comment by Nyumat** [comment]
> I need API you'e using to play the movie, we'e selecting

I see, so I can't exactly give you the API access point due to GitHub's strict DMCA policy. 

However, I can guide you in the right direction. Check out this link, [here.](https://old.reddit.com/r/FREEMEDIAHECKYEAH/wiki/video)

Also, instead of using a third-party API, I'd advise you to craft your own solution by querying the many video hosting services for a challenge. Although, this link should be plenty helpful.

Good luck! @Nyumat  😁
